name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef

      - name: Add .NET tools to PATH
        run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore dependencies
        run: dotnet restore ./src/HostelFinder.WebApi/HostelFinder.WebApi.csproj

      - name: Build
        run: dotnet build --configuration Release ./src/HostelFinder.WebApi/HostelFinder.WebApi.csproj
